"""SQLite database setup and task persistence layer for storing job state and results."""

# We use Python's built-in sqlite3 module — no extra pip dependency required.
# SQLite is a single-file, serverless relational database. For a service that
# processes one video at a time it is perfectly adequate. If you needed high
# write concurrency you would swap in PostgreSQL (via asyncpg or SQLAlchemy-async)
# without changing any of the callers, because the function signatures here form
# a stable interface.

import datetime
import json
import sqlite3
from pathlib import Path
from typing import Any, Dict, Optional

# ---------------------------------------------------------------------------
# Database location
# ---------------------------------------------------------------------------

# Place the DB file at the project root (two directories up from this file).
# Using an absolute path means the location is the same regardless of the
# current working directory when uvicorn is started.
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATABASE_PATH = str(_PROJECT_ROOT / "tasks.db")


# ---------------------------------------------------------------------------
# Connection helper
# ---------------------------------------------------------------------------

def _get_connection() -> sqlite3.Connection:
    """Open and return a new sqlite3 connection with project-wide defaults.

    Why a new connection per call?
    sqlite3 connections are NOT thread-safe by default (check_same_thread=True).
    FastAPI runs synchronous route handlers in a thread-pool executor, so multiple
    requests can be in-flight at the same time on different threads. Opening a
    fresh connection per DB call is the simplest safe pattern for SQLite; a
    connection pool (e.g. via SQLAlchemy) is the production answer.
    """
    conn = sqlite3.connect(
        DATABASE_PATH,
        # PARSE_DECLTYPES instructs sqlite3 to look at the declared column type
        # (e.g. "TIMESTAMP") and pass the stored value through the matching Python
        # converter. Combined with the built-in "timestamp" converter this means
        # created_at comes back as a real datetime object instead of a raw string.
        detect_types=sqlite3.PARSE_DECLTYPES | sqlite3.PARSE_COLNAMES,
        # Allow the same connection to be used on a different thread from the one
        # that created it. Safe here because each call creates its own connection
        # and immediately closes it — there is no shared state.
        check_same_thread=False,
    )
    # Row factory: makes rows behave like dicts so callers write row["task_id"]
    # instead of row[0]. Much safer when columns are added or reordered later.
    conn.row_factory = sqlite3.Row
    return conn


# ---------------------------------------------------------------------------
# Schema initialisation
# ---------------------------------------------------------------------------

def init_db() -> None:
    """Create the tasks table if it does not already exist.

    This is called once at server startup (see app/main.py lifespan context).
    Using IF NOT EXISTS makes it idempotent — safe to call on every restart
    without losing existing rows or raising an error.
    """
    conn = _get_connection()
    try:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS tasks (

                -- Primary key: a UUID4 string generated by the POST handler.
                -- TEXT is the right SQLite type for UUIDs (no native UUID type).
                task_id     TEXT PRIMARY KEY,

                -- Lifecycle state. One of: queued | processing | complete | failed.
                -- NOT NULL because a task without a status is meaningless.
                status      TEXT NOT NULL,

                -- When the task was created. Declared as TIMESTAMP so that
                -- detect_types=PARSE_DECLTYPES converts the stored ISO string
                -- back into a Python datetime on every read.
                created_at  TIMESTAMP NOT NULL,

                -- Absolute path to the uploaded video file saved in data/uploads/.
                video_path  TEXT NOT NULL,

                -- Serialised TaskResult JSON. NULL until the pipeline finishes.
                -- Storing the whole result as a single JSON string avoids the need
                -- for extra tables. Trade-off: you cannot query inside the result
                -- with SQL — you'd have to load and parse every row. Acceptable
                -- for a task-queue pattern where you always fetch by task_id.
                result_json TEXT,

                -- Human-readable error message. NULL unless status == 'failed'.
                error       TEXT
            )
            """
        )
        conn.commit()
    finally:
        # Always close in a finally block so the connection is released even if
        # the CREATE TABLE statement raises an exception.
        conn.close()


# ---------------------------------------------------------------------------
# Write helpers
# ---------------------------------------------------------------------------

def create_task(task_id: str, video_path: str) -> None:
    """Insert a new task row with status 'queued'.

    Parameters
    ----------
    task_id    : UUID4 string generated by the POST /tasks handler.
    video_path : Absolute path to the video saved in data/uploads/.
    """
    conn = _get_connection()
    try:
        conn.execute(
            """
            INSERT INTO tasks (task_id, status, created_at, video_path)
            VALUES (?, ?, ?, ?)
            """,
            # CRITICAL: always use parameterised queries (the ? placeholders).
            # Never use Python string formatting to build SQL — that opens the
            # door to SQL injection even with seemingly safe values like UUIDs.
            (task_id, "queued", datetime.datetime.utcnow(), video_path),
        )
        conn.commit()
    finally:
        conn.close()


def update_task_status(task_id: str, status: str, error: Optional[str] = None) -> None:
    """Update the status field and optionally record an error message.

    Called by the processor to move a task through its lifecycle:
        queued → processing → complete   (happy path)
        queued → processing → failed     (error path)

    Parameters
    ----------
    task_id : The task to update.
    status  : New status string.
    error   : Optional error message; set when status == 'failed'.
    """
    conn = _get_connection()
    try:
        conn.execute(
            "UPDATE tasks SET status = ?, error = ? WHERE task_id = ?",
            (status, error, task_id),
        )
        conn.commit()
    finally:
        conn.close()


def save_task_result(task_id: str, result: Dict[str, Any]) -> None:
    """Persist the pipeline output and mark the task complete in a single UPDATE.

    Doing both in one statement means there is no window where status == 'complete'
    but result_json is still NULL — atomicity within a single SQLite write.

    Parameters
    ----------
    result : A plain Python dict produced by TaskResult.model_dump(by_alias=True).
    """
    conn = _get_connection()
    try:
        conn.execute(
            """
            UPDATE tasks
               SET status      = 'complete',
                   result_json = ?
             WHERE task_id = ?
            """,
            # json.dumps serialises the dict to a JSON string for TEXT storage.
            # json.loads in get_task_result() reverses this when the client asks
            # for the result.
            (json.dumps(result), task_id),
        )
        conn.commit()
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Read helper
# ---------------------------------------------------------------------------

def get_task(task_id: str) -> Optional[Dict[str, Any]]:
    """Fetch a single task row by primary key.

    Returns a plain dict (or None if the task_id does not exist). We convert
    sqlite3.Row to dict before closing the connection so the caller is not
    holding a reference to an object that depends on a closed cursor.

    The dict keys match the column names: task_id, status, created_at,
    video_path, result_json, error.
    """
    conn = _get_connection()
    try:
        cursor = conn.execute(
            "SELECT * FROM tasks WHERE task_id = ?",
            (task_id,),
        )
        # fetchone() returns None automatically when no row matched — no need to
        # check rowcount or catch an exception.
        row = cursor.fetchone()
        if row is None:
            return None
        # dict(row) unpacks the sqlite3.Row into a plain Python dict. Because we
        # set detect_types=PARSE_DECLTYPES on the connection, created_at is already
        # a datetime object at this point — not a raw string.
        return dict(row)
    finally:
        conn.close()
